# +------------------------------------------------------------------------------------+
# |                                                                                    |
# |  ██╗  ██╗ ██████╗ ███╗   ███╗███████╗██╗      █████╗ ██████╗    ██╗   ██╗██╗  ██╗  |
# |  ██║  ██║██╔═████╗████╗ ████║██╔════╝██║     ██╔══██╗██╔══██╗   ██║   ██║██║ ██╔╝  |
# |  ███████║██║██╔██║██╔████╔██║█████╗  ██║     ███████║██████╔╝   ██║   ██║█████╔╝   |
# |  ██╔══██║████╔╝██║██║╚██╔╝██║██╔══╝  ██║     ██╔══██║██╔══██╗   ██║   ██║██╔═██╗   |
# |  ██║  ██║╚██████╔╝██║ ╚═╝ ██║███████╗███████╗██║  ██║██████╔╝██╗╚██████╔╝██║  ██╗  |
# |  ╚═╝  ╚═╝ ╚═════╝ ╚═╝     ╚═╝╚══════╝╚══════╝╚═╝  ╚═╝╚═════╝ ╚═╝ ╚═════╝ ╚═╝  ╚═╝  |
# |                                                                                    |
# +------------------------------------------------------------------------------------+
networks:
  h0melab:
    external: true

services:
  vaultwarden:
    image: vaultwarden/server:latest
    env_file: /env/vaultwarden.env

    volumes:
      - /mnt/docker/vaultwarden/data:/data
      
    ports:
      - 8080:80
      
    networks:
      - h0melab

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 100s
        max_attempts: 10
      placement:
        constraints: [node.role == worker]    
