# +------------------------------------------------------------------------------------+
# |                                                                                    |
# |  ██╗  ██╗ ██████╗ ███╗   ███╗███████╗██╗      █████╗ ██████╗    ██╗   ██╗██╗  ██╗  |
# |  ██║  ██║██╔═████╗████╗ ████║██╔════╝██║     ██╔══██╗██╔══██╗   ██║   ██║██║ ██╔╝  |
# |  ███████║██║██╔██║██╔████╔██║█████╗  ██║     ███████║██████╔╝   ██║   ██║█████╔╝   |
# |  ██╔══██║████╔╝██║██║╚██╔╝██║██╔══╝  ██║     ██╔══██║██╔══██╗   ██║   ██║██╔═██╗   |
# |  ██║  ██║╚██████╔╝██║ ╚═╝ ██║███████╗███████╗██║  ██║██████╔╝██╗╚██████╔╝██║  ██╗  |
# |  ╚═╝  ╚═╝ ╚═════╝ ╚═╝     ╚═╝╚══════╝╚══════╝╚═╝  ╚═╝╚═════╝ ╚═╝ ╚═════╝ ╚═╝  ╚═╝  |
# |                                                                                    |
# +------------------------------------------------------------------------------------+
networks:
  h0melab:
    external: true
    
services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    env_file: /env/uptime.env

    volumes:
      - /mnt/docker/uptime-kuma/data:/app/data

    ports:
      - 3001:3001 
    
    networks:
      - h0melab
      
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 120s  
        max_attempts: 15
