# +------------------------------------------------------------------------------------+
# |                                                                                    |
# |  ██╗  ██╗ ██████╗ ███╗   ███╗███████╗██╗      █████╗ ██████╗    ██╗   ██╗██╗  ██╗  |
# |  ██║  ██║██╔═████╗████╗ ████║██╔════╝██║     ██╔══██╗██╔══██╗   ██║   ██║██║ ██╔╝  |
# |  ███████║██║██╔██║██╔████╔██║█████╗  ██║     ███████║██████╔╝   ██║   ██║█████╔╝   |
# |  ██╔══██║████╔╝██║██║╚██╔╝██║██╔══╝  ██║     ██╔══██║██╔══██╗   ██║   ██║██╔═██╗   |
# |  ██║  ██║╚██████╔╝██║ ╚═╝ ██║███████╗███████╗██║  ██║██████╔╝██╗╚██████╔╝██║  ██╗  |
# |  ╚═╝  ╚═╝ ╚═════╝ ╚═╝     ╚═╝╚══════╝╚══════╝╚═╝  ╚═╝╚═════╝ ╚═╝ ╚═════╝ ╚═╝  ╚═╝  |
# |                                                                                    |
# +------------------------------------------------------------------------------------+

networks:
  h0melab:
    external: true
    
services:
  redis:
    image: redis:latest
    
    ports:
      - 6379:6379
    
    networks:
      - h0melab

    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 100s
        max_attempts: 15
      placement:
        constraints: 
          - node.role == worker
