# +------------------------------------------------------------------------------------+
# |                                                                                    |
# |  ██╗  ██╗ ██████╗ ███╗   ███╗███████╗██╗      █████╗ ██████╗    ██╗   ██╗██╗  ██╗  |
# |  ██║  ██║██╔═████╗████╗ ████║██╔════╝██║     ██╔══██╗██╔══██╗   ██║   ██║██║ ██╔╝  |
# |  ███████║██║██╔██║██╔████╔██║█████╗  ██║     ███████║██████╔╝   ██║   ██║█████╔╝   |
# |  ██╔══██║████╔╝██║██║╚██╔╝██║██╔══╝  ██║     ██╔══██║██╔══██╗   ██║   ██║██╔═██╗   |
# |  ██║  ██║╚██████╔╝██║ ╚═╝ ██║███████╗███████╗██║  ██║██████╔╝██╗╚██████╔╝██║  ██╗  |
# |  ╚═╝  ╚═╝ ╚═════╝ ╚═╝     ╚═╝╚══════╝╚══════╝╚═╝  ╚═╝╚═════╝ ╚═╝ ╚═════╝ ╚═╝  ╚═╝  |
# |                                                                                    |
# +------------------------------------------------------------------------------------+
version: "3.1"

networks:
  h0melab:
    external: true

services:
  semaphore:
    image: semaphoreui/semaphore:latest
    env_file: /env/semaphore.env

    volumes:
      - /mnt/docker/ansible:/ansible  
    
    ports:
      - 3000:3000

    networks:
      - h0melab

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 120s
        max_attempts: 15
      placement:
        constraints: [node.role == worker]
